# Run against a kit root. The fixture never builds or changes an R package.
runChecks <- function(root) {
  Work <- tempfile("installer á ")
  dir.create(Work)
  on.exit(unlink(Work, recursive = TRUE), add = TRUE)
  Fixture <- file.path(Work, "product")
  dir.create(Fixture)
  stopifnot(file.copy(file.path(root, "install"), Fixture, recursive = TRUE))
  for (DIR in c("lib", "cli/bin", "cli/helpers")) {
    dir.create(file.path(Fixture, DIR), recursive = TRUE)
  }
  writeLines(c("Package: stats", paste0("Version: ", utils::packageVersion("stats"))),
             file.path(Fixture, "lib/DESCRIPTION"))
  writeLines('list(command = "installerprobe", minimum = "0.0.0")',
             file.path(Fixture, "install/requirements.R"))
  Launcher <- file.path(Fixture, "cli/bin/installerprobe")
  writeLines(c("#!/bin/sh", "echo installerprobe"), Launcher)
  writeLines("invisible(NULL)", file.path(Fixture, "cli/main.R"))
  writeLines("invisible(NULL)", file.path(Fixture, "cli/helpers/retired.R"))
  Files <- c("bin/installerprobe", "main.R", "helpers/retired.R")
  Manifest <- file.path(Fixture, "install/manifest.json")
  jsonlite::write_json(list(manifest_version = 1L, files = Files), Manifest, auto_unbox = TRUE)
  Rscript <- file.path(R.home("bin"), "Rscript")
  Manager <- file.path(Fixture, "install/cli/manage.R")
  runManager <- function(action, prefix, success = TRUE) {
    OUT <- suppressWarnings(system2(Rscript, shQuote(c("--vanilla", Manager, action, prefix)),
                                    stdout = TRUE, stderr = TRUE))
    Status <- attr(OUT, "status")
    if (is.null(Status)) Status <- 0L
    if ((Status == 0L) != success) stop(paste(OUT, collapse = "\n"))
    invisible(OUT)
  }
  receiptPath <- function(prefix) file.path(prefix, "libexec/installerprobe/install.json")
  Prefix <- file.path(Work, "retirement")
  runManager("check", Prefix)
  stopifnot(!dir.exists(Prefix))
  runManager("install", Prefix)
  Created <- jsonlite::read_json(receiptPath(Prefix), simplifyVector = TRUE)$created
  unlink(file.path(Fixture, "cli/helpers/retired.R"))
  jsonlite::write_json(list(manifest_version = 1L, files = Files[-3L]), Manifest, auto_unbox = TRUE)
  runManager("install", Prefix)
  Record <- jsonlite::read_json(receiptPath(Prefix), simplifyVector = TRUE)
  stopifnot(!file.exists(file.path(Prefix, "libexec/installerprobe/helpers/retired.R")),
            all(Created %in% Record$created))
  Hash <- tools::md5sum(file.path(Prefix, c(Record$file, "libexec/installerprobe/install.json")))
  writeLines(c("#!/bin/sh", "echo broken >&2", "exit 42"), Launcher)
  runManager("install", Prefix, success = FALSE)
  stopifnot(identical(Hash, tools::md5sum(names(Hash))))
  writeLines(c("#!/bin/sh", "echo installerprobe"), Launcher)
  Foreign <- file.path(Prefix, "libexec/installerprobe/foreign.txt")
  writeLines("keep", Foreign)
  runManager("uninstall", Prefix)
  stopifnot(file.exists(Foreign), !file.exists(receiptPath(Prefix)),
            !file.exists(file.path(Prefix, "bin/installerprobe")))
  Prefix <- file.path(Work, "empty")
  runManager("install", Prefix)
  runManager("uninstall", Prefix)
  stopifnot(!dir.exists(Prefix))
  Prefix <- file.path(Work, "receipt")
  runManager("install", Prefix)
  Outside <- file.path(Work, "foreign.txt")
  writeLines("keep", Outside)
  Record <- jsonlite::read_json(receiptPath(Prefix), simplifyVector = TRUE)
  Record$file <- c(Record$file, "../foreign.txt")
  Record$md5 <- c(Record$md5, unname(tools::md5sum(Outside)))
  jsonlite::write_json(Record, receiptPath(Prefix), auto_unbox = TRUE)
  runManager("uninstall", Prefix, success = FALSE)
  stopifnot(file.exists(Outside), file.exists(file.path(Prefix, "bin/installerprobe")))
  Prefix <- file.path(Work, "symlink")
  Outside <- file.path(Work, "outside")
  dir.create(file.path(Prefix, "libexec/installerprobe"), recursive = TRUE)
  dir.create(Outside)
  stopifnot(file.symlink(Outside, file.path(Prefix, "libexec/installerprobe/helpers")))
  writeLines("invisible(NULL)", file.path(Fixture, "cli/helpers/retired.R"))
  jsonlite::write_json(list(manifest_version = 1L, files = Files), Manifest, auto_unbox = TRUE)
  runManager("install", Prefix, success = FALSE)
  stopifnot(!length(list.files(Outside)))
  message("PASS: check, receipt confinement, retirement, rollback, symlinks, uninstall")
}
runChecks(normalizePath(commandArgs(TRUE)[1L], mustWork = TRUE))
