test_that("directory resources work under accented source and project paths", {
  Root <- tempfile("ngr \u00e1 ")
  dir.create(Root)
  on.exit(unlink(Root, recursive = TRUE), add = TRUE)
  Source <- file.path(Root, "source")
  Project <- file.path(Root, "project \u00e1")
  dir.create(Source)
  dir.create(Project)
  dir.create(file.path(Source, "data"))
  writeLines("second", file.path(Source, "data/z.txt"))
  writeLines("first", file.path(Source, "data/a.txt"))
  Manifest <- file.path(Source, "manifest.json")
  jsonlite::write_json(list(schemaVersion = 1L, id = "unicode", resources = list(
    list(from = "data", to = "resources", ownership = "managed")
  )), Manifest, auto_unbox = TRUE)
  OUT <- NGR::pullResources(from = Manifest, root = Project)
  expect_identical(OUT$actions$path, c("resources/a.txt", "resources/z.txt"))
  expect_identical(readLines(file.path(Project, "resources/a.txt")), "first")
  expect_identical(readLines(file.path(Project, "resources/z.txt")), "second")
  expect_false(NGR::compareResources(root = Project)$changed)
})
