on:
  push:
    branches: [main, dev]
  workflow_dispatch:

name: pkgdown

permissions:
  contents: write

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v5

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: ./.github/actions/aom-r
        with:
          system-packages: libuv1-dev libcurl4-openssl-dev libssl-dev libxml2-dev libgit2-dev libfontconfig1-dev libfreetype6-dev libharfbuzz-dev libfribidi-dev libpng-dev libtiff-dev libjpeg-dev libwebp-dev

      - name: Install R dependencies
        shell: Rscript {0}
        run: |
          source("install/package.R")
          installRequirements(path = "lib", library = .libPaths()[1L], packages = "pkgdown", dependencies = TRUE)

      - name: Build site
        working-directory: lib
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = TRUE)
        shell: Rscript {0}

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: lib/docs
